### Recuperamos todas las peliculas
GET http://localhost:3000/movies

### Recuperamos todas las peliculas con un filtro
GET http://localhost:3000/movies?genre=fantasy

### Recuperamos una pelicula por id
GET http://localhost:3000/movies/deb36d42-ac50-11ef-b2f4-d89ef342e8b0

### Crear una pelicula
POST http://localhost:3000/movies
Content-Type: application/json

{
    "title": "The godfather test",
    "year": 1975,
    "director": "Francis Ford Coppola",
    "duration": 175,
    "poster": "https://i.ebayimg.com/images/g/4goAAOSwMyBe7hnQ/s-l1200.webp",
    "genre": [
        "Crime",
        "Drama",
        "Action",
        "Adventure"
    ],
    "rate": 5.0
}

### Actualizar una pelicula (pero sólo una parte de ella)
PATCH http://localhost:3000/movies/072dee7d-ac39-11ef-b2f4-d89ef342e8b0
Content-Type: application/json

{
    "year": 2000,
    "duration": 200
}

### Borrar una pelicula pasando su id
DELETE http://localhost:3000/movies/326246b5-ac14-11ef-b2f4-d89ef342e8b0
Content-Type: application/json